name: Metrics
on:
  schedule: [{ cron: "0 * * * *" }] # setiap jam
  workflow_dispatch:
permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: dimasyoga42 #ini ganti username github kalian
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_anilist: yes
          plugin_anilist_medias: anime
          plugin_anilist_user: dimasyoga21 #ini bisa diganti dengan username anilist kalian, nanti saya akan berikan tau caranya..
          plugin_anilist_sections: favorites, watching, characters
          plugin_anilist_limit: 1
          config_timezone: Asia/Jakarta